package.loaded["laserwave.palette"] = nil
package.loaded["laserwave.transform.kitty"] = nil

local shipwright = require("shipwright")
local lush = require("shipwright.transform.lush")
local overwrite = require("shipwright.transform.overwrite")
local patchwrite = require("shipwright.transform.patchwrite")
local prepend = require("shipwright.transform.prepend")

local colorscheme = require("laserwave").config()
local palette = require("laserwave.palette")
local kitty = require("laserwave.transform.kitty")

local function to_vim_terminal_colors(vimcolors)
  termcolors = {
    string.format("let g:terminal_color_0 = '%s'", palette.terminal.BLACK),
    string.format("let g:terminal_color_1 = '%s'", palette.terminal.RED),
    string.format("let g:terminal_color_2 = '%s'", palette.terminal.GREEN),
    string.format("let g:terminal_color_3 = '%s'", palette.terminal.YELLOW),
    string.format("let g:terminal_color_4 = '%s'", palette.terminal.BLUE),
    string.format("let g:terminal_color_5 = '%s'", palette.terminal.MAGENTA),
    string.format("let g:terminal_color_6 = '%s'", palette.terminal.CYAN),
    string.format("let g:terminal_color_7 = '%s'", palette.terminal.WHITE),
    string.format("let g:terminal_color_8 = '%s'", palette.terminal.BRIGHT_BLACK),
    string.format("let g:terminal_color_9 = '%s'", palette.terminal.BRIGHT_RED),
    string.format("let g:terminal_color_10 = '%s'", palette.terminal.BRIGHT_GREEN),
    string.format("let g:terminal_color_11 = '%s'", palette.terminal.BRIGHT_YELLOW),
    string.format("let g:terminal_color_12 = '%s'", palette.terminal.BRIGHT_BLUE),
    string.format("let g:terminal_color_13 = '%s'", palette.terminal.BRIGHT_MAGENTA),
    string.format("let g:terminal_color_14 = '%s'", palette.terminal.BRIGHT_CYAN),
    string.format("let g:terminal_color_15 = '%s'", palette.terminal.BRIGHT_WHITE),
  }

  return vim.list_extend(vimcolors, termcolors)
end

shipwright.run(
  colorscheme,
  lush.to_vimscript,
  lush.vim_compatible_vimscript,
  to_vim_terminal_colors,
  { prepend, '" Autogenerated by shipright.nvim' },
  { patchwrite, "colors/laserwave.vim", '" theme start', '" theme end' }
)

shipwright.run(palette, kitty, { overwrite, "dist/kitty/laserwave.conf" })
