package.loaded["laserwave.palette"] = nil
package.loaded["laserwave.transform.kitty"] = nil

local shipwright = require("shipwright")
local lush = require("shipwright.transform.lush")
local overwrite = require("shipwright.transform.overwrite")
local patchwrite = require("shipwright.transform.patchwrite")
local prepend = require("shipwright.transform.prepend")

local colorscheme = require("laserwave").config()
local palette = require("laserwave.palette")
local kitty = require("laserwave.transform.kitty")

shipwright.run(
  colorscheme,
  lush.to_vimscript,
  lush.vim_compatible_vimscript,
  { prepend, '" Autogenerated by shipright.nvim' },
  { patchwrite, "colors/laserwave.vim", '" theme start', '" theme end' }
)

shipwright.run(palette, kitty, { overwrite, "dist/kitty/laserwave.conf" })
