-- GENERATED ON 2026-01-16 AT 16:41:48
-- name:     laserwave-hi_c
-- author:   Eric Eldredge <lettertwo@gmail.com>
-- license:  MIT
-- upstream: https://github.com/lettertwo/laserwave.nvim/colors/laserwave-hi_c.lua
-- blurb:    Based on LaserWave for VSCode by Jared Jones
local specs = {
--%% begin compiled_specs %%--
  spec = {
    Normal = {fg = "#FFFFFF", bg = "#19151E"},
    NormalNC = {link = "Normal"},
    Add = {fg = "#1ED3EC"},
    Attribute = {fg = "#FF52BF"},
    Boolean = {fg = "#FFE261"},
    Change = {fg = "#3FEABF"},
    Character = {fg = "#3FEABF"},
    CommandMode = {bg = "#35454E"},
    Comment = {fg = "#B4ABBE"},
    Conceal = {fg = "#FFFFFF", bg = "#19151E"},
    EndOfBuffer = {link = "Conceal"},
    SpecialKey = {link = "Conceal"},
    Constant = {fg = "#FFE261"},
    CurSearch = {reverse = true},
    IncSearch = {link = "CurSearch"},
    Substitute = {link = "CurSearch"},
    Cursor = {fg = "#FFFFFF", bg = "#422B49", reverse = true},
    CursorIM = {link = "Cursor"},
    lCursor = {link = "Cursor"},
    CursorLine = {bg = "#30253A"},
    ColorColumn = {link = "CursorLine"},
    CursorColumn = {link = "CursorLine"},
    CursorLineFold = {fg = "#D887F5", bg = "#30253A"},
    CursorLineNr = {fg = "#9FE0BD", bg = "#30253A"},
    CursorLineSign = {fg = "#D887F5", bg = "#30253A"},
    Define = {fg = "#FF52BF"},
    Delete = {fg = "#FF52BF"},
    Delimiter = {fg = "#B4A8C8"},
    DiffAdd = {fg = "#1ED3EC", bg = "#282236"},
    DiffChange = {fg = "#1ED3EC", bg = "#282236"},
    DiffDelete = {fg = "#FF52BF", bg = "#271E2E"},
    DiffText = {fg = "#3FEABF", bg = "#272339"},
    DiffTextAdd = {fg = "#1ED3EC", bg = "#282236"},
    Directory = {fg = "#1ED3EC"},
    Error = {fg = "#FF3E7B"},
    ErrorMsg = {fg = "#FF3E7B"},
    Float = {fg = "#D887F5"},
    FloatBorder = {fg = "#FF52BF", bg = "#17131C"},
    FloatTitle = {fg = "#FF52BF", bg = "#17131C"},
    FoldColumn = {fg = "#65557A", bg = "#19151E"},
    Folded = {fg = "#65557A", bg = "#3D3449"},
    Function = {fg = "#FF52BF"},
    Identifier = {fg = "#FFFFFF"},
    Ignore = {fg = "#B4A8C8"},
    Include = {fg = "#1ED3EC", italic = true},
    InsertMode = {bg = "#353F55"},
    Keyword = {fg = "#1ED3EC", italic = true},
    LineNr = {fg = "#65557A"},
    Macro = {fg = "#FF52BF"},
    MatchParen = {fg = "#FF52BF", bold = true},
    ModeCommand = {fg = "#FFE261"},
    ModeInsert = {fg = "#3FEABF"},
    ModeMsg = {fg = "#B4A8C8", bold = true},
    ModeNormal = {fg = "#1ED3EC"},
    ModeReplace = {fg = "#FF52BF"},
    ModeSelect = {fg = "#D887F5"},
    ModeTerminal = {fg = "#FFE261"},
    ModeTerminalNormal = {fg = "#FFE261"},
    ModeVisual = {fg = "#D887F5"},
    MoreMsg = {fg = "#1ED3EC"},
    NonText = {fg = "#B4A8C8"},
    MsgArea = {link = "NonText"},
    PreProc = {link = "NonText"},
    NormalFloat = {fg = "#FFFFFF", bg = "#17131C"},
    Pmenu = {link = "NormalFloat"},
    PmenuSbar = {link = "NormalFloat"},
    NormalMode = {bg = "#363767"},
    Number = {fg = "#D887F5"},
    OkMsg = {fg = "#3FEABF"},
    Operator = {fg = "#3FEABF"},
    PmenuThumb = {bg = "#B4A8C8"},
    PreCondit = {fg = "#1ED3EC"},
    Punctuation = {fg = "#B4A8C8"},
    Question = {fg = "#1ED3EC"},
    QuickFixLine = {bg = "#382A45", bold = true},
    ReplaceMode = {bg = "#422B49"},
    Search = {bg = "#744690"},
    SelectMode = {bg = "#412F50"},
    SignColumn = {fg = "#65557A", bg = "#19151E"},
    Special = {fg = "#3FEABF"},
    SpellBad = {sp = "#FF3E7B", undercurl = true},
    SpellCap = {sp = "#FFB85B", undercurl = true},
    SpellLocal = {sp = "#1ED3EC", undercurl = true},
    SpellRare = {sp = "#B4ABBE", undercurl = true},
    Statement = {fg = "#1ED3EC"},
    StatusLine = {fg = "#FFFFFF", bg = "#17131C"},
    StatusLineNC = {fg = "#B4A8C8", bg = "#17131C"},
    String = {fg = "#ACDFEF"},
    TabLine = {fg = "#FFFFFF", bg = "#17131C"},
    TabLineFill = {fg = "#FFFFFF", bg = "#17131C"},
    TabLineSel = {fg = "#19151E", bg = "#FF52BF"},
    Tag = {fg = "#3FEABF"},
    TerminalBlack = {fg = "#B4ABBE"},
    TerminalBlue = {fg = "#1ED3EC"},
    TerminalBrightBlack = {fg = "#D887F5"},
    TerminalBrightBlue = {fg = "#1ED3EC"},
    TerminalBrightCyan = {fg = "#ACDFEF"},
    TerminalBrightGreen = {fg = "#3FEABF"},
    TerminalBrightMagenta = {fg = "#FF52BF"},
    TerminalBrightRed = {fg = "#FF3E7B"},
    TerminalBrightWhite = {fg = "#FFFFFF"},
    TerminalBrightYellow = {fg = "#FFB85B"},
    TerminalCyan = {fg = "#ACDFEF"},
    TerminalGreen = {fg = "#3FEABF"},
    TerminalMagenta = {fg = "#D887F5"},
    TerminalMode = {bg = "#35454E"},
    TerminalNormalMode = {bg = "#35454E"},
    TerminalRed = {fg = "#FF52BF"},
    TerminalWhite = {fg = "#FFFFFF"},
    TerminalYellow = {fg = "#FFE261"},
    Title = {fg = "#1ED3EC", bold = true},
    Todo = {fg = "#FFE261"},
    Type = {fg = "#D887F5"},
    Underlined = {underline = true},
    VirtualText = {fg = "#B4A8C8", bg = "#231E29"},
    Visual = {bg = "#382A45"},
    PmenuSel = {link = "Visual"},
    VisualNOS = {link = "Visual"},
    WildMenu = {link = "Visual"},
    VisualMode = {bg = "#412F50"},
    WarningMsg = {fg = "#FFB85B"},
    Whitespace = {fg = "#B4A8C8"},
    WinBar = {fg = "#FFFFFF", bg = "#17131C"},
    WinBarNC = {fg = "#B4A8C8", bg = "#17131C"},
    WinSeparator = {fg = "#FF52BF"},
    healthError = {fg = "#FF3E7B"},
    healthSuccess = {fg = "#3FEABF"},
    healthWarning = {fg = "#FFB85B"},
  },
  plugins = {
    alpha = {
      StartLogo1 = {fg = "#1ED3EC"},
      StartLogo10 = {fg = "#873E8B"},
      StartLogo11 = {fg = "#7A3A78"},
      StartLogo12 = {fg = "#6C3568"},
      StartLogo13 = {fg = "#603566"},
      StartLogo14 = {fg = "#553461"},
      StartLogo15 = {fg = "#4A315B"},
      StartLogo16 = {fg = "#402E52"},
      StartLogo17 = {fg = "#372B49"},
      StartLogo18 = {fg = "#2F263F"},
      StartLogo19 = {fg = "#282134"},
      StartLogo2 = {fg = "#31C1EF"},
      StartLogo20 = {fg = "#201B29"},
      StartLogo3 = {fg = "#3CAEF6"},
      StartLogo4 = {fg = "#6699F1"},
      StartLogo5 = {fg = "#8183EB"},
      StartLogo6 = {fg = "#936CE3"},
      StartLogo7 = {fg = "#A152DA"},
      StartLogo8 = {fg = "#9E47BE"},
      StartLogo9 = {fg = "#9342A1"},
    },
    blink = {
      BlinkCmpKindClass = {fg = "#D887F5"},
      BlinkCmpKindConstant = {fg = "#FFE261"},
      BlinkCmpKindConstructor = {fg = "#FF52BF"},
      BlinkCmpKindCopilot = {fg = "#FFE261"},
      BlinkCmpKindEnum = {fg = "#D887F5"},
      BlinkCmpKindEnumMember = {fg = "#D887F5"},
      BlinkCmpKindEvent = {fg = "#D887F5"},
      BlinkCmpKindField = {fg = "#3FEABF"},
      BlinkCmpKindFunction = {fg = "#FF52BF"},
      BlinkCmpKindInterface = {fg = "#D887F5"},
      BlinkCmpKindKeyword = {fg = "#1ED3EC"},
      BlinkCmpKindMethod = {fg = "#FF52BF"},
      BlinkCmpKindModule = {},
      BlinkCmpKindOperator = {fg = "#3FEABF"},
      BlinkCmpKindProperty = {fg = "#3FEABF"},
      BlinkCmpKindReference = {fg = "#FFE261"},
      BlinkCmpKindSnippet = {fg = "#B4A8C8"},
      BlinkCmpKindStruct = {fg = "#D887F5"},
      BlinkCmpKindText = {fg = "#B4ABBE"},
      BlinkCmpKindTypeParameter = {fg = "#D887F5"},
      BlinkCmpKindUnit = {fg = "#D887F5"},
      BlinkCmpKindValue = {fg = "#1ED3EC"},
      BlinkCmpKindVariable = {fg = "#FFFFFF"},
      BlinkCmpLabel = {fg = "#B4ABBE"},
      BlinkCmpLabelDeprecated = {fg = "#B4A8C8", strikethrough = true},
      BlinkCmpLabelMatch = {fg = "#FF52BF"},
      BlinkCmpMenu = {link = "Float"},
      BlinkCmpDocBorder = {link = "FloatBorder"},
      BlinkCmpMenuBorder = {link = "FloatBorder"},
      BlinkCmpSignatureHelpBorder = {link = "FloatBorder"},
    },
    cmp = {
      CmpItemAbbr = {fg = "#B4ABBE"},
      CmpItemAbbrDeprecated = {fg = "#B4A8C8", strikethrough = true},
      CmpItemAbbrMatch = {fg = "#FF52BF"},
      CmpItemAbbrMatchFuzzy = {fg = "#FF52BF"},
      CmpItemKindClass = {fg = "#D887F5"},
      CmpItemKindConstant = {fg = "#FFE261"},
      CmpItemKindConstructor = {fg = "#FF52BF"},
      CmpItemKindCopilot = {fg = "#FFE261"},
      CmpItemKindEnum = {fg = "#D887F5"},
      CmpItemKindEnumMember = {fg = "#D887F5"},
      CmpItemKindEvent = {fg = "#D887F5"},
      CmpItemKindField = {fg = "#3FEABF"},
      CmpItemKindFunction = {fg = "#FF52BF"},
      CmpItemKindInterface = {fg = "#D887F5"},
      CmpItemKindKeyword = {fg = "#1ED3EC"},
      CmpItemKindMethod = {fg = "#FF52BF"},
      CmpItemKindModule = {},
      CmpItemKindOperator = {fg = "#3FEABF"},
      CmpItemKindProperty = {fg = "#3FEABF"},
      CmpItemKindReference = {fg = "#FFE261"},
      CmpItemKindSnippet = {fg = "#B4A8C8"},
      CmpItemKindStruct = {fg = "#D887F5"},
      CmpItemKindText = {fg = "#B4ABBE"},
      CmpItemKindTypeParameter = {fg = "#D887F5"},
      CmpItemKindUnit = {fg = "#D887F5"},
      CmpItemKindValue = {fg = "#1ED3EC"},
      CmpItemKindVariable = {fg = "#FFFFFF"},
      CmpItemMenu = {fg = "#B4A8C8"},
    },
    git = {
      GitGutterAdd = {fg = "#1ED3EC"},
      GitGutterChange = {fg = "#3FEABF"},
      GitGutterDelete = {fg = "#FF52BF"},
      GitSignsAdd = {fg = "#1ED3EC"},
      GitSignsChange = {fg = "#3FEABF"},
      GitSignsDelete = {fg = "#FF52BF"},
      gitblame = {link = "VirtualText"},
    },
    lsp = {
      DiagnosticError = {fg = "#FF3E7B"},
      DiagnosticHint = {fg = "#B4ABBE"},
      DiagnosticInfo = {fg = "#1ED3EC"},
      DiagnosticOk = {fg = "#3FEABF"},
      DiagnosticUnderlineError = {sp = "#FF3E7B", undercurl = true},
      DiagnosticUnderlineHint = {sp = "#B4ABBE", undercurl = true},
      DiagnosticUnderlineInfo = {sp = "#1ED3EC", undercurl = true},
      DiagnosticUnderlineOk = {sp = "#3FEABF", undercurl = true},
      DiagnosticUnderlineWarn = {sp = "#FFB85B", undercurl = true},
      DiagnosticVirtualTextError = {fg = "#FF3E7B", bg = "#51001E"},
      DiagnosticVirtualTextHint = {fg = "#B4ABBE", bg = "#302937"},
      DiagnosticVirtualTextInfo = {fg = "#1ED3EC", bg = "#02353C"},
      DiagnosticVirtualTextOk = {fg = "#3FEABF", bg = "#083A2D"},
      DiagnosticVirtualTextWarn = {fg = "#FFB85B", bg = "#442B00"},
      DiagnosticWarn = {fg = "#FFB85B"},
      LspInfoBorder = {link = "FloatBorder"},
      LspReferenceRead = {bg = "#382A45"},
      LspReferenceText = {bg = "#382A45"},
      LspReferenceWrite = {bg = "#382A45"},
      LspCodeLensSeparator = {link = "VirtualText"},
      LspSignatureActiveParameter = {link = "VirtualText"},
      ["@lsp.type.enumMember"] = {link = "@constant"},
      ["@lsp.type.decorator"] = {link = "@function"},
      ["@lsp.type.function"] = {link = "@function"},
      ["@lsp.type.macro"] = {link = "@macro"},
      ["@lsp.type.method"] = {link = "@method"},
      ["@lsp.type.namespace"] = {link = "@namespace"},
      ["@lsp.type.parameter"] = {link = "@parameter"},
      ["@lsp.type.property"] = {link = "@property"},
      ["@lsp.type.struct"] = {link = "@structure"},
      ["@lsp.type.class"] = {link = "@type"},
      ["@lsp.type.enum"] = {link = "@type"},
      ["@lsp.type.interface"] = {link = "@type"},
      ["@lsp.type.type"] = {link = "@type"},
      ["@lsp.type.variable"] = {link = "@variable"},
    },
    mini_pick = {
      MiniPickPreviewLine = {link = "CursorLine"},
      MiniPickBorder = {link = "FloatBorder"},
      MiniPickBorderText = {link = "FloatTitle"},
      MiniPickBorderBusy = {fg = "#FFB85B", bg = "#17131C"},
      MiniPickCursor = {fg = "#FF52BF", bg = "#17131C"},
      MiniPickMatchCurrent = {bg = "#30253A", bold = true},
      MiniPickMatchRanges = {fg = "#FF52BF", bold = true},
      MiniPickPreviewRegion = {fg = "#FF52BF", bg = "#382A45", bold = true},
      MiniPickNormal = {link = "NormalFloat"},
      MiniPickHeader = {link = "Title"},
      MiniPickPrompt = {link = "Title"},
      MiniPickMatchMarked = {link = "Visual"},
    },
    neotree = {
      NeoTreeFloatBorder = {link = "FloatBorder"},
      NeoTreeFloatTitle = {link = "FloatTitle"},
      NeoTreeTitleBar = {link = "FloatTitle"},
      NeoTreeGitAdded = {fg = "#1ED3EC", bold = true},
      NeoTreeGitConflict = {fg = "#FF3E7B", bold = true},
      NeoTreeGitDeleted = {fg = "#FF52BF", bold = true},
      NeoTreeGitIgnored = {fg = "#B4A8C8", bold = true},
      NeoTreeGitModified = {fg = "#3FEABF", bold = true},
      NeoTreeGitUntracked = {fg = "#B4ABBE"},
    },
    obsidian = {
      ObsidianDone = {fg = "#B4ABBE"},
      ObsidianExtLinkIcon = {fg = "#B4ABBE"},
      ObsidianHighlightText = {bg = "#FF52BF"},
      ObsidianRefText = {fg = "#ACDFEF", underline = true},
      ObsidianRightArrow = {fg = "#FFB85B"},
      ObsidianTag = {fg = "#3FEABF", italic = true},
      ObsidianTilde = {fg = "#FF3E7B"},
      ObsidianTodo = {fg = "#1ED3EC"},
    },
    occurrence = {
      OccurrenceCurrent = {reverse = true, underline = true},
      OccurrenceMark = {underline = true},
      OccurrenceMatch = {link = "Visual"},
    },
    package_info = {
      PackageInfoOutdatedVersion = {fg = "#FF3E7B"},
      PackageInfoUpToDateVersion = {fg = "#3FEABF"},
    },
    semantic_highlights = {
      ["@lsp.typemod.variable.defaultLibrary"] = {link = "Constant"},
      ["@lsp.typemod.variable.static"] = {link = "Constant"},
      ["@lsp.type.decorator"] = {link = "Define"},
      ["@lsp.typemod.variable.callable"] = {link = "Function"},
      ["@lsp.typemod.variable.injected"] = {link = "Identifier"},
      ["@lsp.type.class"] = {link = "Type"},
      ["@lsp.type.keyword"] = {link = "Type"},
      ["@lsp.type.variable"] = {},
    },
    snacks = {
      SnacksDashboardDesc = {link = "Normal"},
      SnacksDashboardFooter = {fg = "#B4A8C8"},
      SnacksDashboardHeader = {fg = "#1ED3EC"},
      SnacksDashboardHeader1 = {fg = "#1ED3EC"},
      SnacksDashboardHeader10 = {fg = "#873E8B"},
      SnacksDashboardHeader11 = {fg = "#7A3A78"},
      SnacksDashboardHeader12 = {fg = "#6C3568"},
      SnacksDashboardHeader13 = {fg = "#603566"},
      SnacksDashboardHeader14 = {fg = "#553461"},
      SnacksDashboardHeader15 = {fg = "#4A315B"},
      SnacksDashboardHeader16 = {fg = "#402E52"},
      SnacksDashboardHeader17 = {fg = "#372B49"},
      SnacksDashboardHeader18 = {fg = "#2F263F"},
      SnacksDashboardHeader19 = {fg = "#282134"},
      SnacksDashboardHeader2 = {fg = "#31C1EF"},
      SnacksDashboardHeader20 = {fg = "#201B29"},
      SnacksDashboardHeader3 = {fg = "#3CAEF6"},
      SnacksDashboardHeader4 = {fg = "#6699F1"},
      SnacksDashboardHeader5 = {fg = "#8183EB"},
      SnacksDashboardHeader6 = {fg = "#936CE3"},
      SnacksDashboardHeader7 = {fg = "#A152DA"},
      SnacksDashboardHeader8 = {fg = "#9E47BE"},
      SnacksDashboardHeader9 = {fg = "#9342A1"},
      SnacksDashboardIcon = {fg = "#ACDFEF"},
      SnacksPickerGitStatusAdded = {fg = "#1ED3EC"},
      SnacksPickerGitStatusDeleted = {fg = "#FF52BF"},
      SnacksPickerGitStatusModified = {fg = "#3FEABF"},
      SnacksPickerGitStatusStaged = {fg = "#1ED3EC"},
      SnacksPickerGitStatusUnmerged = {fg = "#FF3E7B"},
    },
    space = {
      ExtraWhitespace = {bg = "#FF3E7B"},
      MiniTrailspace = {link = "ExtraWhitespace"},
      SnacksIndentBlank = {link = "ExtraWhitespace"},
      IblIndent = {fg = "#4B3C61"},
      IblWhitespace = {link = "IblIndent"},
      IndentBlanklineChar = {link = "IblIndent"},
      SnacksIndent = {link = "IblIndent"},
      IblScope = {fg = "#826CA0"},
      IndentBlanklineContextChar = {link = "IblScope"},
      MiniIndentscopeSymbol = {link = "IblScope"},
      SnacksIndentChunk = {link = "IblScope"},
      SnacksIndentScope = {link = "IblScope"},
    },
    telescope = {
      TelescopeBorder = {link = "FloatBorder"},
      TelescopePromptBorder = {link = "FloatBorder"},
      TelescopePreviewTitle = {link = "FloatTitle"},
      TelescopePromptTitle = {link = "FloatTitle"},
      TelescopeResultsTitle = {link = "FloatTitle"},
      TelescopeNormal = {link = "NormalFloat"},
      TelescopePromptNormal = {link = "NormalFloat"},
      TelescopePromptPrefix = {fg = "#FF52BF", bg = "#17131C"},
      TelescopeSelection = {link = "Visual"},
    },
    treesitter = {
      ["@tag.attribute"] = {link = "Attribute"},
      ["@constant.builtin"] = {link = "Constant"},
      ["@constant.macro"] = {link = "Constant"},
      ["@keyword.export"] = {link = "Constant"},
      ["@property.id"] = {link = "Constant"},
      ["@type.builtin"] = {link = "Constant"},
      ["@type.tag"] = {link = "Constant"},
      ["@variable.builtin"] = {link = "Constant"},
      ["@punctuation.delimiter"] = {link = "Delimiter"},
      ["@tag.delimiter"] = {link = "Delimiter"},
      ["@constructor"] = {link = "Function"},
      ["@property.class"] = {link = "Function"},
      ["@keyword.operator"] = {link = "Operator"},
      ["@punctuation"] = {link = "Punctuation"},
      TreesitterContext = {bg = "#17131C"},
      TreesitterContextLineNumber = {fg = "#744690", bg = "#17131C"},
      TreesitterContextSeparator = {fg = "#0F0C13"},
      ["@keyword.jsdoc"] = {link = "Type"},
      ["@property"] = {fg = "#1ED3EC"},
      ["@string.escape"] = {fg = "#D887F5"},
      ["@string.regex"] = {fg = "#1ED3EC"},
      ["@text.diff.add"] = {fg = "#1ED3EC"},
      ["@text.diff.change"] = {fg = "#3FEABF"},
      ["@text.diff.delete"] = {fg = "#FF52BF"},
    },
  },
--%% end compiled_specs %%--
}
local function apply_colors(groups, extend)
  for group, attrs in pairs(groups) do
    if extend then
      local base = vim.api.nvim_get_hl(0, { name = group }) or {}
      vim.api.nvim_set_hl(0, group, vim.tbl_extend("force", base, attrs))
    else
      vim.api.nvim_set_hl(0, group, attrs)
    end
  end
end
local function apply_terminal_colors()
  vim.g.terminal_color_0 = "#B4ABBE"
  vim.g.terminal_color_1 = "#FF52BF"
  vim.g.terminal_color_2 = "#1ED3EC"
  vim.g.terminal_color_3 = "#FFE261"
  vim.g.terminal_color_4 = "#1ED3EC"
  vim.g.terminal_color_5 = "#D887F5"
  vim.g.terminal_color_6 = "#ACDFEF"
  vim.g.terminal_color_7 = "#FFFFFF"
  vim.g.terminal_color_8 = "#D887F5"
  vim.g.terminal_color_9 = "#FF3E7B"
  vim.g.terminal_color_10 = "#3FEABF"
  vim.g.terminal_color_11 = "#FFB85B"
  vim.g.terminal_color_12 = "#1ED3EC"
  vim.g.terminal_color_13 = "#FF52BF"
  vim.g.terminal_color_14 = "#ACDFEF"
  vim.g.terminal_color_15 = "#FFFFFF"
end
-- Load config and apply colors
vim.cmd("highlight clear")
vim.o.background = "dark"
vim.o.termguicolors = true
vim.g.colors_name = "laserwave-hi_c"
require("laserwave").set_flavor("hi_c")
local cfg = require("laserwave").get_config()
apply_colors(specs.spec)
if cfg.terminal_colors then
  apply_terminal_colors()
end
if cfg.transparent then
  apply_colors({ Normal = { bg = nil } }, true)
end
apply_colors({
  Comment = { italic = cfg.italic_comments },
  Function = { italic = cfg.italic_functions },
  Statement = { italic = cfg.italic_keywords },
  Keyword = { italic = cfg.italic_keywords },
  Include = { italic = cfg.italic_keywords },
  Identifier = { italic = cfg.italic_variables },
}, true)
if cfg.treesitter and specs.plugins.treesitter then
  apply_colors(specs.plugins.treesitter)
end
if cfg.semantic_highlights and specs.plugins.semantic_highlights then
  apply_colors(specs.plugins.semantic_highlights)
end
for key, value in pairs(cfg.plugins) do
  if value and specs.plugins[key] then
    apply_colors(specs.plugins[key])
  end
end
