-- GENERATED ON 2026-01-20 AT 17:41:27
-- name:     laserwave
-- author:   Eric Eldredge <lettertwo@gmail.com>
-- license:  MIT
-- upstream: https://github.com/lettertwo/laserwave.nvim/colors/laserwave.lua
-- blurb:    Based on LaserWave for VSCode by Jared Jones
local specs = {
--%% begin compiled_specs %%--
  spec = {
    Normal = {fg = "#FFFFFF", bg = "#27212E"},
    NormalNC = {link = "Normal"},
    Add = {fg = "#40B4C4"},
    Attribute = {fg = "#EB64B9"},
    Boolean = {fg = "#FFE261"},
    Change = {fg = "#74DFC4"},
    Character = {fg = "#74DFC4"},
    Comment = {fg = "#91889B"},
    Conceal = {fg = "#FFFFFF", bg = "#27212E"},
    EndOfBuffer = {link = "Conceal"},
    SpecialKey = {link = "Conceal"},
    Constant = {fg = "#FFE261"},
    CurSearch = {reverse = true},
    IncSearch = {link = "CurSearch"},
    Substitute = {link = "CurSearch"},
    Cursor = {fg = "#FFFFFF", bg = "#4C3554", reverse = true},
    CursorIM = {link = "Cursor"},
    lCursor = {link = "Cursor"},
    CursorLine = {bg = "#392E42"},
    ColorColumn = {link = "CursorLine"},
    CursorColumn = {link = "CursorLine"},
    CursorLineFold = {fg = "#3F334A", bg = "#392E42"},
    CursorLineNr = {fg = "#B0CFBE", bg = "#392E42"},
    CursorLineSign = {fg = "#3F334A", bg = "#392E42"},
    Define = {fg = "#EB64B9"},
    Delete = {fg = "#EB64B9"},
    Delimiter = {fg = "#7B6995"},
    DiagnosticError = {fg = "#FF3E7B"},
    DiagnosticHint = {fg = "#91889B"},
    DiagnosticInfo = {fg = "#40B4C4"},
    DiagnosticOk = {fg = "#74DFC4"},
    DiagnosticUnderlineError = {sp = "#FF3E7B", undercurl = true},
    DiagnosticUnderlineHint = {sp = "#91889B", undercurl = true},
    DiagnosticUnderlineInfo = {sp = "#40B4C4", undercurl = true},
    DiagnosticUnderlineOk = {sp = "#74DFC4", undercurl = true},
    DiagnosticUnderlineWarn = {sp = "#FFB85B", undercurl = true},
    DiagnosticVirtualTextError = {fg = "#FF3E7B", bg = "#51001E"},
    DiagnosticVirtualTextHint = {fg = "#91889B", bg = "#27232C"},
    DiagnosticVirtualTextInfo = {fg = "#40B4C4", bg = "#0A2E33"},
    DiagnosticVirtualTextOk = {fg = "#74DFC4", bg = "#18372F"},
    DiagnosticVirtualTextWarn = {fg = "#FFB85B", bg = "#442B00"},
    DiagnosticWarn = {fg = "#FFB85B"},
    DiffAdd = {fg = "#40B4C4", bg = "#322B43"},
    DiffChange = {fg = "#40B4C4", bg = "#322B43"},
    DiffDelete = {fg = "#EB64B9", bg = "#35293D"},
    DiffText = {fg = "#74DFC4", bg = "#332F48"},
    DiffTextAdd = {fg = "#40B4C4", bg = "#322B43"},
    Directory = {fg = "#40B4C4"},
    Error = {fg = "#FF3E7B"},
    ErrorMsg = {fg = "#FF3E7B"},
    Float = {fg = "#B381C5"},
    FloatBorder = {fg = "#EB64B9", bg = "#241E2B"},
    LspInfoBorder = {link = "FloatBorder"},
    FloatTitle = {fg = "#EB64B9", bg = "#241E2B"},
    FoldColumn = {fg = "#4F435F", bg = "#27212E"},
    Folded = {fg = "#4F435F", bg = "#3B3245"},
    Function = {fg = "#EB64B9"},
    Identifier = {fg = "#FFFFFF"},
    Ignore = {fg = "#7B6995"},
    Include = {fg = "#40B4C4", italic = true},
    Keyword = {fg = "#40B4C4", italic = true},
    LineNr = {fg = "#4F435F"},
    LspCodeLensSeparator = {fg = "#7B6995", bg = "#3F334A"},
    LspReferenceRead = {bg = "#3F334A"},
    LspReferenceText = {bg = "#3F334A"},
    LspReferenceWrite = {bg = "#3F334A"},
    LspSignatureActiveParameter = {fg = "#7B6995", bg = "#3F334A"},
    Macro = {fg = "#EB64B9"},
    MatchParen = {fg = "#EB64B9", bold = true},
    ModeCommand = {fg = "#FFE261"},
    ModeInsert = {fg = "#74DFC4"},
    ModeMsg = {fg = "#7B6995", bold = true},
    ModeNormal = {fg = "#40B4C4"},
    ModeReplace = {fg = "#EB64B9"},
    ModeSelect = {fg = "#3F334A"},
    ModeTerminal = {fg = "#FFE261"},
    ModeTerminalNormal = {fg = "#FFE261"},
    ModeVisual = {fg = "#3F334A"},
    MoreMsg = {fg = "#40B4C4"},
    NonText = {fg = "#7B6995"},
    MsgArea = {link = "NonText"},
    PreProc = {link = "NonText"},
    NormalFloat = {fg = "#FFFFFF", bg = "#241E2B"},
    Pmenu = {link = "NormalFloat"},
    PmenuSbar = {link = "NormalFloat"},
    Number = {fg = "#B381C5"},
    OkMsg = {fg = "#74DFC4"},
    Operator = {fg = "#74DFC4"},
    PmenuThumb = {bg = "#7B6995"},
    PreCondit = {fg = "#40B4C4"},
    Punctuation = {fg = "#7B6995"},
    Question = {fg = "#40B4C4"},
    QuickFixLine = {bg = "#3F334A", bold = true},
    Search = {bg = "#684E79"},
    SignColumn = {fg = "#4F435F", bg = "#27212E"},
    Special = {fg = "#74DFC4"},
    SpellBad = {sp = "#FF3E7B", undercurl = true},
    SpellCap = {sp = "#FFB85B", undercurl = true},
    SpellLocal = {sp = "#40B4C4", undercurl = true},
    SpellRare = {sp = "#91889B", undercurl = true},
    Statement = {fg = "#40B4C4"},
    StatusLine = {fg = "#91889B", bg = "#241E2B"},
    StatusLineNC = {fg = "#7B6995", bg = "#241E2B"},
    String = {fg = "#B4DCE7"},
    TabLine = {fg = "#FFFFFF", bg = "#241E2B"},
    TabLineFill = {fg = "#FFFFFF", bg = "#241E2B"},
    TabLineSel = {fg = "#27212E", bg = "#EB64B9"},
    Tag = {fg = "#74DFC4"},
    TerminalBlack = {fg = "#91889B"},
    TerminalBlue = {fg = "#40B4C4"},
    TerminalBrightBlack = {fg = "#B381C5"},
    TerminalBrightBlue = {fg = "#40B4C4"},
    TerminalBrightCyan = {fg = "#B4DCE7"},
    TerminalBrightGreen = {fg = "#74DFC4"},
    TerminalBrightMagenta = {fg = "#EB64B9"},
    TerminalBrightRed = {fg = "#FF3E7B"},
    TerminalBrightWhite = {fg = "#FFFFFF"},
    TerminalBrightYellow = {fg = "#FFB85B"},
    TerminalCyan = {fg = "#B4DCE7"},
    TerminalGreen = {fg = "#74DFC4"},
    TerminalMagenta = {fg = "#B381C5"},
    TerminalRed = {fg = "#EB64B9"},
    TerminalWhite = {fg = "#FFFFFF"},
    TerminalYellow = {fg = "#FFE261"},
    Title = {fg = "#40B4C4", bold = true},
    Todo = {fg = "#40B4C4"},
    Type = {fg = "#B381C5"},
    Underlined = {underline = true},
    Visual = {bg = "#3F334A"},
    PmenuSel = {link = "Visual"},
    VisualNOS = {link = "Visual"},
    WildMenu = {link = "Visual"},
    WarningMsg = {fg = "#FFB85B"},
    Whitespace = {fg = "#7B6995"},
    WinBar = {fg = "#FFFFFF", bg = "#241E2B"},
    WinBarNC = {fg = "#7B6995", bg = "#241E2B"},
    WinSeparator = {fg = "#EB64B9"},
    healthError = {fg = "#FF3E7B"},
    healthSuccess = {fg = "#74DFC4"},
    healthWarning = {fg = "#FFB85B"},
  },
  plugins = {
    blink = {
      BlinkCmpKindClass = {fg = "#B381C5"},
      BlinkCmpKindConstant = {fg = "#FFE261"},
      BlinkCmpKindConstructor = {fg = "#EB64B9"},
      BlinkCmpKindCopilot = {fg = "#FFE261"},
      BlinkCmpKindEnum = {fg = "#B381C5"},
      BlinkCmpKindEnumMember = {fg = "#B381C5"},
      BlinkCmpKindEvent = {fg = "#B381C5"},
      BlinkCmpKindField = {fg = "#74DFC4"},
      BlinkCmpKindFunction = {fg = "#EB64B9"},
      BlinkCmpKindInterface = {fg = "#B381C5"},
      BlinkCmpKindKeyword = {fg = "#40B4C4"},
      BlinkCmpKindMethod = {fg = "#EB64B9"},
      BlinkCmpKindModule = {fg = "#7B6995"},
      BlinkCmpKindOperator = {fg = "#74DFC4"},
      BlinkCmpKindProperty = {fg = "#74DFC4"},
      BlinkCmpKindReference = {fg = "#FFE261"},
      BlinkCmpKindSnippet = {fg = "#7B6995"},
      BlinkCmpKindStruct = {fg = "#B381C5"},
      BlinkCmpKindText = {fg = "#91889B"},
      BlinkCmpKindTypeParameter = {fg = "#B381C5"},
      BlinkCmpKindUnit = {fg = "#B381C5"},
      BlinkCmpKindValue = {fg = "#40B4C4"},
      BlinkCmpKindVariable = {fg = "#FFFFFF"},
      BlinkCmpLabel = {fg = "#91889B"},
      BlinkCmpLabelDeprecated = {fg = "#7B6995", strikethrough = true},
      BlinkCmpLabelMatch = {fg = "#EB64B9"},
      BlinkCmpMenu = {link = "Float"},
      BlinkCmpDocBorder = {link = "FloatBorder"},
      BlinkCmpMenuBorder = {link = "FloatBorder"},
      BlinkCmpSignatureHelpBorder = {link = "FloatBorder"},
    },
    cmp = {
      CmpItemAbbr = {fg = "#91889B"},
      CmpItemAbbrDeprecated = {fg = "#7B6995", strikethrough = true},
      CmpItemAbbrMatch = {fg = "#EB64B9"},
      CmpItemAbbrMatchFuzzy = {fg = "#EB64B9"},
      CmpItemKindClass = {fg = "#B381C5"},
      CmpItemKindConstant = {fg = "#FFE261"},
      CmpItemKindConstructor = {fg = "#EB64B9"},
      CmpItemKindCopilot = {fg = "#FFE261"},
      CmpItemKindEnum = {fg = "#B381C5"},
      CmpItemKindEnumMember = {fg = "#B381C5"},
      CmpItemKindEvent = {fg = "#B381C5"},
      CmpItemKindField = {fg = "#74DFC4"},
      CmpItemKindFunction = {fg = "#EB64B9"},
      CmpItemKindInterface = {fg = "#B381C5"},
      CmpItemKindKeyword = {fg = "#40B4C4"},
      CmpItemKindMethod = {fg = "#EB64B9"},
      CmpItemKindModule = {fg = "#7B6995"},
      CmpItemKindOperator = {fg = "#74DFC4"},
      CmpItemKindProperty = {fg = "#74DFC4"},
      CmpItemKindReference = {fg = "#FFE261"},
      CmpItemKindSnippet = {fg = "#7B6995"},
      CmpItemKindStruct = {fg = "#B381C5"},
      CmpItemKindText = {fg = "#91889B"},
      CmpItemKindTypeParameter = {fg = "#B381C5"},
      CmpItemKindUnit = {fg = "#B381C5"},
      CmpItemKindValue = {fg = "#40B4C4"},
      CmpItemKindVariable = {fg = "#FFFFFF"},
      CmpItemMenu = {fg = "#7B6995"},
    },
    git = {
      GitGutterAdd = {fg = "#40B4C4"},
      GitGutterChange = {fg = "#74DFC4"},
      GitGutterDelete = {fg = "#EB64B9"},
      GitSignsAdd = {fg = "#40B4C4"},
      GitSignsChange = {fg = "#74DFC4"},
      GitSignsDelete = {fg = "#EB64B9"},
      gitblame = {fg = "#7B6995", bg = "#3F334A"},
    },
    mini_pick = {
      MiniPickPreviewLine = {link = "CursorLine"},
      MiniPickBorder = {link = "FloatBorder"},
      MiniPickBorderText = {link = "FloatTitle"},
      MiniPickBorderBusy = {fg = "#FFB85B", bg = "#241E2B"},
      MiniPickCursor = {fg = "#EB64B9", bg = "#241E2B"},
      MiniPickMatchCurrent = {bg = "#3F334A", bold = true},
      MiniPickMatchRanges = {fg = "#EB64B9", bold = true},
      MiniPickPreviewRegion = {fg = "#EB64B9", bg = "#3F334A", bold = true},
      MiniPickNormal = {link = "NormalFloat"},
      MiniPickHeader = {link = "Title"},
      MiniPickPrompt = {link = "Title"},
      MiniPickMatchMarked = {link = "Visual"},
    },
    neotree = {
      NeoTreeFloatBorder = {link = "FloatBorder"},
      NeoTreeFloatTitle = {link = "FloatTitle"},
      NeoTreeTitleBar = {link = "FloatTitle"},
      NeoTreeGitAdded = {fg = "#40B4C4", bold = true},
      NeoTreeGitConflict = {fg = "#FF3E7B", bold = true},
      NeoTreeGitDeleted = {fg = "#EB64B9", bold = true},
      NeoTreeGitIgnored = {fg = "#7B6995", bold = true},
      NeoTreeGitModified = {fg = "#74DFC4", bold = true},
      NeoTreeGitUntracked = {fg = "#91889B"},
    },
    obsidian = {
      ObsidianDone = {fg = "#91889B"},
      ObsidianExtLinkIcon = {fg = "#91889B"},
      ObsidianHighlightText = {bg = "#EB64B9"},
      ObsidianRefText = {fg = "#B4DCE7", underline = true},
      ObsidianRightArrow = {fg = "#FFB85B"},
      ObsidianTag = {fg = "#74DFC4", italic = true},
      ObsidianTilde = {fg = "#FF3E7B"},
      ObsidianTodo = {fg = "#40B4C4"},
    },
    occurrence = {
      OccurrenceCurrent = {reverse = true, underline = true},
      OccurrenceMark = {underline = true},
      OccurrenceMatch = {link = "Visual"},
    },
    package_info = {
      PackageInfoOutdatedVersion = {fg = "#FF3E7B"},
      PackageInfoUpToDateVersion = {fg = "#74DFC4"},
    },
    semantic_highlights = {
      ["@lsp.type.decorator"] = {link = "@attribute"},
      ["@lsp.type.deriveHelper"] = {link = "@attribute"},
      ["@lsp.type.boolean"] = {link = "@boolean"},
      ["@lsp.type.comment"] = {link = "@comment"},
      ["@lsp.typemod.enumMember.defaultLibrary"] = {link = "@constant.builtin"},
      ["@lsp.type.enumMember"] = {link = "@constant"},
      ["@lsp.typemod.variable.static"] = {link = "@constant"},
      ["@lsp.typemod.function.defaultLibrary"] = {link = "@function.builtin"},
      ["@lsp.typemod.macro.defaultLibrary"] = {link = "@function.builtin"},
      ["@lsp.typemod.method.defaultLibrary"] = {link = "@function.builtin"},
      ["@lsp.typemod.variable.callable"] = {link = "@function"},
      ["@lsp.typemod.keyword.async"] = {link = "@keyword.coroutine"},
      ["@lsp.type.lifetime"] = {link = "@keyword.storage"},
      ["@lsp.type.keyword.lua"] = {link = "@keyword"},
      ["@lsp.typemod.keyword.injected"] = {link = "@keyword"},
      ["@lsp.type.class"] = {link = "@lsp.type.keyword"},
      ["@lsp.type.unresolvedReference"] = {sp = "#FF3E7B", undercurl = true},
      ["@lsp.type.interface"] = {link = "@lsp.type"},
      ["@lsp.type.formatSpecifier"] = {link = "@markup.list"},
      ["@lsp.type.namespace"] = {link = "@module"},
      ["@lsp.type.class.lua"] = {link = "@none"},
      ["@lsp.type.number"] = {link = "@number"},
      ["@lsp.type.operator"] = {link = "@operator"},
      ["@lsp.typemod.operator.injected"] = {link = "@operator"},
      ["@lsp.type.property"] = {link = "@property"},
      ["@lsp.type.escapeSequence"] = {link = "@string.escape"},
      ["@lsp.type.string"] = {link = "@string"},
      ["@lsp.typemod.string.injected"] = {link = "@string"},
      ["@lsp.type.builtinType"] = {link = "@type.builtin"},
      ["@lsp.typemod.class.defaultLibrary"] = {link = "@type.builtin"},
      ["@lsp.typemod.enum.defaultLibrary"] = {link = "@type.builtin"},
      ["@lsp.typemod.struct.defaultLibrary"] = {link = "@type.builtin"},
      ["@lsp.typemod.type.defaultLibrary"] = {link = "@type.builtin"},
      ["@lsp.typemod.typeAlias.defaultLibrary"] = {link = "@type.builtin"},
      ["@lsp.type.typeAlias"] = {link = "@type.definition"},
      ["@lsp.type.enum"] = {link = "@type"},
      ["@lsp.type.keyword"] = {link = "@type"},
      ["@lsp.type.selfKeyword"] = {link = "@variable.builtin"},
      ["@lsp.type.selfTypeKeyword"] = {link = "@variable.builtin"},
      ["@lsp.typemod.variable.defaultLibrary"] = {link = "@variable.builtin"},
      ["@lsp.type.parameter"] = {link = "@variable.parameter"},
      ["@lsp.type.generic"] = {link = "@variable"},
      ["@lsp.type.namespace.python"] = {link = "@variable"},
      ["@lsp.type.variable"] = {link = "@variable"},
      ["@lsp.typemod.variable.injected"] = {link = "@variable"},
    },
    snacks = {
      SnacksDashboardDesc = {link = "Normal"},
      SnacksDashboardFooter = {fg = "#7B6995"},
      SnacksDashboardHeader = {fg = "#40B4C4"},
      SnacksDashboardHeader1 = {fg = "#40B4C4"},
      SnacksDashboardHeader10 = {fg = "#85498A"},
      SnacksDashboardHeader11 = {fg = "#7C457B"},
      SnacksDashboardHeader12 = {fg = "#763B72"},
      SnacksDashboardHeader13 = {fg = "#693B6F"},
      SnacksDashboardHeader14 = {fg = "#5E3A6B"},
      SnacksDashboardHeader15 = {fg = "#533865"},
      SnacksDashboardHeader16 = {fg = "#49355D"},
      SnacksDashboardHeader17 = {fg = "#413255"},
      SnacksDashboardHeader18 = {fg = "#392F4B"},
      SnacksDashboardHeader19 = {fg = "#332A42"},
      SnacksDashboardHeader2 = {fg = "#47A8C8"},
      SnacksDashboardHeader20 = {fg = "#2D2638"},
      SnacksDashboardHeader3 = {fg = "#4C9CCF"},
      SnacksDashboardHeader4 = {fg = "#528DDE"},
      SnacksDashboardHeader5 = {fg = "#727CDA"},
      SnacksDashboardHeader6 = {fg = "#866BD2"},
      SnacksDashboardHeader7 = {fg = "#9459C9"},
      SnacksDashboardHeader8 = {fg = "#9451B3"},
      SnacksDashboardHeader9 = {fg = "#8E4D9C"},
      SnacksDashboardIcon = {fg = "#B4DCE7"},
      SnacksPickerGitStatusAdded = {fg = "#40B4C4"},
      SnacksPickerGitStatusDeleted = {fg = "#EB64B9"},
      SnacksPickerGitStatusModified = {fg = "#74DFC4"},
      SnacksPickerGitStatusStaged = {fg = "#40B4C4"},
      SnacksPickerGitStatusUnmerged = {fg = "#FF3E7B"},
    },
    space = {
      ExtraWhitespace = {bg = "#FF3E7B"},
      MiniTrailspace = {link = "ExtraWhitespace"},
      SnacksIndentBlank = {link = "ExtraWhitespace"},
      IblIndent = {fg = "#372E40"},
      IblWhitespace = {link = "IblIndent"},
      IndentBlanklineChar = {link = "IblIndent"},
      SnacksIndent = {link = "IblIndent"},
      IblScope = {fg = "#78578A"},
      IndentBlanklineContextChar = {link = "IblScope"},
      MiniIndentscopeSymbol = {link = "IblScope"},
      SnacksIndentChunk = {link = "IblScope"},
      SnacksIndentScope = {link = "IblScope"},
    },
    telescope = {
      TelescopeBorder = {link = "FloatBorder"},
      TelescopePromptBorder = {link = "FloatBorder"},
      TelescopePreviewTitle = {link = "FloatTitle"},
      TelescopePromptTitle = {link = "FloatTitle"},
      TelescopeResultsTitle = {link = "FloatTitle"},
      TelescopeNormal = {link = "NormalFloat"},
      TelescopePromptNormal = {link = "NormalFloat"},
      TelescopePromptPrefix = {fg = "#EB64B9", bg = "#241E2B"},
      TelescopeSelection = {link = "Visual"},
    },
    treesitter = {
      ["@attribute"] = {link = "Attribute"},
      ["@tag.attribute"] = {link = "Attribute"},
      ["@boolean"] = {link = "Boolean"},
      ["@character"] = {link = "Character"},
      ["@comment"] = {link = "Comment"},
      ["@keyword.conditional"] = {link = "Conditional"},
      ["@constant"] = {link = "Constant"},
      ["@keyword.debug"] = {link = "Debug"},
      ["@keyword.directive.define"] = {link = "Define"},
      ["@punctuation.delimiter"] = {link = "Delimiter"},
      ["@tag.delimiter"] = {link = "Delimiter"},
      ["@diff.plus"] = {link = "DiffAdd"},
      ["@diff.minus"] = {link = "DiffDelete"},
      ["@diff.delta"] = {link = "DiffText"},
      ["@keyword.exception"] = {link = "Error"},
      ["@function"] = {link = "Function"},
      ["@variable"] = {link = "Identifier"},
      ["@keyword.import"] = {link = "Include"},
      ["@module"] = {link = "Include"},
      ["@keyword"] = {link = "Keyword"},
      ["@label"] = {link = "Label"},
      ["@tag"] = {link = "Label"},
      ["@number"] = {link = "Number"},
      ["@operator"] = {link = "Operator"},
      ["@annotation"] = {link = "PreProc"},
      ["@keyword.directive"] = {link = "PreProc"},
      ["@punctuation"] = {link = "Punctuation"},
      ["@string.special"] = {link = "Special"},
      ["@markup.quote"] = {link = "String"},
      ["@markup.raw"] = {link = "String"},
      ["@string"] = {link = "String"},
      TreesitterContext = {bg = "#241E2B"},
      TreesitterContextLineNumber = {fg = "#B0CFBE", bg = "#241E2B"},
      TreesitterContextSeparator = {fg = "#241E2B"},
      ["@type"] = {link = "Type"},
      ["@property"] = {link = "Variable"},
      ["@character.special"] = {fg = "#40B4C4"},
      ["@comment.error"] = {fg = "#FF3E7B"},
      ["@comment.hint"] = {fg = "#91889B"},
      ["@comment.info"] = {fg = "#40B4C4"},
      ["@comment.note"] = {fg = "#91889B"},
      ["@comment.todo"] = {fg = "#40B4C4"},
      ["@comment.warning"] = {fg = "#FFB85B"},
      ["@comment.documentation"] = {link = "@comment"},
      ["@attribute.builtin"] = {link = "@constant"},
      ["@constant.builtin"] = {link = "@constant"},
      ["@constant.macro"] = {link = "@constant"},
      ["@function.builtin"] = {link = "@constant"},
      ["@keyword.export"] = {link = "@constant"},
      ["@macro"] = {link = "@constant"},
      ["@module.builtin"] = {link = "@constant"},
      ["@namespace.builtin"] = {link = "@constant"},
      ["@property.id"] = {link = "@constant"},
      ["@tag.builtin"] = {link = "@constant"},
      ["@type.builtin"] = {link = "@constant"},
      ["@type.tag"] = {link = "@constant"},
      ["@variable.builtin"] = {link = "@constant"},
      ["@variable.parameter.builtin"] = {link = "@constant"},
      ["@property.class"] = {link = "@constructor"},
      ["@function.macro"] = {link = "@function.builtin"},
      ["@function.method.call"] = {link = "@function.method"},
      ["@method"] = {link = "@function.method"},
      ["@constructor"] = {link = "@function"},
      ["@function.call"] = {link = "@function"},
      ["@function.method"] = {link = "@function"},
      ["@keyword.conditional.ternary"] = {link = "@keyword.conditional"},
      ["@keyword.coroutine"] = {link = "@keyword"},
      ["@keyword.function"] = {link = "@keyword"},
      ["@keyword.modifier"] = {link = "@keyword"},
      ["@keyword.repeat"] = {link = "@keyword"},
      ["@keyword.return"] = {link = "@keyword"},
      ["@markup.heading"] = {bold = true},
      ["@markup.heading.1"] = {fg = "#40B4C4", bold = true},
      ["@markup.heading.2"] = {fg = "#4C9CCF", bold = true},
      ["@markup.heading.3"] = {fg = "#727CDA", bold = true},
      ["@markup.heading.4"] = {fg = "#9459C9", bold = true},
      ["@markup.heading.5"] = {fg = "#8E4D9C", bold = true},
      ["@markup.heading.6"] = {fg = "#7C457B", bold = true},
      ["@markup.italic"] = {italic = true},
      ["@markup.link.label"] = {link = "@markup.link"},
      ["@markup.link.url"] = {link = "@markup.link"},
      ["@markup.list"] = {fg = "#74DFC4"},
      ["@markup.list.checked"] = {fg = "#91889B"},
      ["@markup.list.unchecked"] = {fg = "#40B4C4"},
      ["@markup.raw.block"] = {link = "@markup.raw"},
      ["@markup.strikethrough"] = {strikethrough = true},
      ["@markup.strong"] = {bold = true},
      ["@markup.underline"] = {underline = true},
      ["@none"] = {},
      ["@variable.member"] = {link = "@none"},
      ["@markup.math"] = {link = "@number"},
      ["@number.float"] = {link = "@number"},
      ["@keyword.operator"] = {link = "@operator"},
      ["@variable.parameter"] = {link = "@parameter"},
      ["@punctuation.bracket"] = {link = "@punctuation"},
      ["@punctuation.special"] = {link = "@punctuation"},
      ["@string.escape"] = {fg = "#B381C5"},
      ["@string.regexp"] = {fg = "#40B4C4"},
      ["@string.special.url"] = {fg = "#74DFC4", underline = true},
      ["@markup.link"] = {link = "@string.special.url"},
      ["@string.special.path"] = {link = "@string.special"},
      ["@string.special.symbol"] = {link = "@string.special"},
      ["@string.documentation"] = {link = "@string"},
      ["@structure"] = {fg = "#40B4C4"},
      ["@keyword.jsdoc"] = {link = "@type"},
      ["@keyword.type"] = {link = "@type"},
      ["@namespace"] = {link = "@type"},
      ["@type.definition"] = {link = "@type"},
      ["@parameter"] = {link = "@variable"},
    },
  },
--%% end compiled_specs %%--
}
local function apply_colors(groups, extend)
  for group, attrs in pairs(groups) do
    if extend then
      local base = vim.api.nvim_get_hl(0, { name = group }) or {}
      vim.api.nvim_set_hl(0, group, vim.tbl_extend("force", base, attrs))
    else
      vim.api.nvim_set_hl(0, group, attrs)
    end
  end
end
local function apply_terminal_colors()
  vim.g.terminal_color_0 = "#91889B"
  vim.g.terminal_color_1 = "#EB64B9"
  vim.g.terminal_color_2 = "#40B4C4"
  vim.g.terminal_color_3 = "#FFE261"
  vim.g.terminal_color_4 = "#40B4C4"
  vim.g.terminal_color_5 = "#B381C5"
  vim.g.terminal_color_6 = "#B4DCE7"
  vim.g.terminal_color_7 = "#FFFFFF"
  vim.g.terminal_color_8 = "#B381C5"
  vim.g.terminal_color_9 = "#FF3E7B"
  vim.g.terminal_color_10 = "#74DFC4"
  vim.g.terminal_color_11 = "#FFB85B"
  vim.g.terminal_color_12 = "#40B4C4"
  vim.g.terminal_color_13 = "#EB64B9"
  vim.g.terminal_color_14 = "#B4DCE7"
  vim.g.terminal_color_15 = "#FFFFFF"
end
-- Load config and apply colors
-- Hide all semantic highlights
for _, group in ipairs(vim.fn.getcompletion("@lsp", "highlight")) do
  vim.api.nvim_set_hl(0, group, {})
end
-- Reset all highlights to the defaults
vim.cmd("highlight clear")
vim.o.background = "dark"
vim.o.termguicolors = true
vim.g.colors_name = "laserwave"
require("laserwave").set_flavor("original")
local cfg = require("laserwave").get_config()
apply_colors(specs.spec)
if cfg.terminal_colors then
  apply_terminal_colors()
end
if cfg.transparent then
  apply_colors({ Normal = { bg = nil } }, true)
end
apply_colors({
  Comment = { italic = cfg.italic_comments },
  Function = { italic = cfg.italic_functions },
  Statement = { italic = cfg.italic_keywords },
  Keyword = { italic = cfg.italic_keywords },
  Include = { italic = cfg.italic_keywords },
  Identifier = { italic = cfg.italic_variables },
}, true)
for key, value in pairs(cfg.plugins) do
  if value and specs.plugins[key] then
    apply_colors(specs.plugins[key])
  end
end
if cfg.treesitter and specs.plugins.treesitter then
  apply_colors(specs.plugins.treesitter)
end
if cfg.semantic_highlights and specs.plugins.semantic_highlights then
  apply_colors(specs.plugins.semantic_highlights)
end
