if exists('g:colors_name')
    highlight clear
endif

let g:colors_name = 'laserwave'
set background=dark

if has('nvim') && (!exists('g:laserwave_compat') || g:laserwave_compat == 0)
    lua require("laserwave").apply()
    finish
endif

" let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

if &background !=# 'dark'
    finish
endif

" theme start
" Autogenerated by shipright.nvim
highlight Normal guifg=#FFFFFF guibg=#27212E guisp=NONE
highlight! link NormalNC Normal
highlight Bold guifg=NONE guibg=NONE guisp=NONE gui=bold cterm=bold
highlight Boolean guifg=#FFE25F guibg=NONE guisp=NONE
highlight Character guifg=#75DFC4 guibg=NONE guisp=NONE
highlight CmpItemAbbr guifg=#91889B guibg=NONE guisp=NONE
highlight CmpItemAbbrDeprecated guifg=#7C6A96 guibg=NONE guisp=NONE gui=strikethrough cterm=strikethrough
highlight CmpItemAbbrMatch guifg=#EB65B9 guibg=NONE guisp=NONE
highlight CmpItemAbbrMatchFuzzy guifg=#EB65B9 guibg=NONE guisp=NONE
highlight CmpItemMenu guifg=#7C6A96 guibg=NONE guisp=NONE
highlight Comment guifg=#91889B guibg=NONE guisp=NONE gui=italic cterm=italic
highlight! link CmpItemKindText Comment
highlight Conceal guifg=#27212E guibg=#27212E guisp=NONE
highlight! link EndOfBuffer Conceal
highlight! link SpecialKey Conceal
highlight Constant guifg=#FFE25F guibg=NONE guisp=NONE
highlight! link CmpItemKindConstant Constant
highlight! link CmpItemKindReference Constant
highlight! link TSConstBuiltin Constant
highlight! link TSConstMacro Constant
highlight! link TSVariableBuiltin Constant
highlight! link CursorIM Cursor
highlight! link TermCursor Cursor
highlight! link TermCursorNC Cursor
highlight! link lCursor Cursor
highlight CursorLine guifg=NONE guibg=#302938 guisp=NONE
highlight! link ColorColumn CursorLine
highlight! link CursorColumn CursorLine
highlight CursorLineNr guifg=#91889B guibg=#302938 guisp=NONE
highlight DiagnosticError guifg=#FF3D7A guibg=NONE guisp=NONE
highlight DiagnosticHint guifg=#91889B guibg=NONE guisp=NONE
highlight DiagnosticInfo guifg=#41B5C5 guibg=NONE guisp=NONE
highlight DiagnosticUnderlineError guifg=NONE guibg=NONE guisp=#FF3D7A gui=undercurl cterm=undercurl
highlight DiagnosticUnderlineHint guifg=NONE guibg=NONE guisp=#91889B gui=undercurl cterm=undercurl
highlight DiagnosticUnderlineInfo guifg=NONE guibg=NONE guisp=#41B5C5 gui=undercurl cterm=undercurl
highlight DiagnosticUnderlineWarn guifg=NONE guibg=NONE guisp=#FFB961 gui=undercurl cterm=undercurl
highlight DiagnosticVirtualTextError guifg=#FF3D7A guibg=#52001E guisp=NONE
highlight DiagnosticVirtualTextHint guifg=#91889B guibg=#28242D guisp=NONE
highlight DiagnosticVirtualTextInfo guifg=#41B5C5 guibg=#0A2E33 guisp=NONE
highlight DiagnosticVirtualTextWarn guifg=#FFB961 guibg=#452B00 guisp=NONE
highlight DiagnosticWarn guifg=#FFB961 guibg=NONE guisp=NONE
highlight DiffAdd guifg=NONE guibg=#39434D guisp=NONE
highlight DiffChange guifg=NONE guibg=#39434D guisp=NONE
highlight DiffDelete guifg=NONE guibg=#4F354C guisp=NONE
highlight DiffText guifg=NONE guibg=#614040 guisp=NONE
highlight Directory guifg=#41B5C5 guibg=NONE guisp=NONE
highlight Error guifg=#FF3D7A guibg=NONE guisp=NONE
highlight ErrorMsg guifg=#FF3D7A guibg=NONE guisp=NONE
highlight ExtraWhitespace guifg=NONE guibg=#FF3D7A guisp=NONE
highlight FoldColumn guifg=#7C6A96 guibg=#27212E guisp=NONE
highlight Folded guifg=#7C6A96 guibg=#3C3347 guisp=NONE
highlight Function guifg=#EB65B9 guibg=NONE guisp=NONE
highlight! link CmpItemKindConstructor Function
highlight! link CmpItemKindFunction Function
highlight! link CmpItemKindMethod Function
highlight! link TSConstructor Function
highlight GitGutterAdd guifg=#41B5C5 guibg=NONE guisp=NONE
highlight GitGutterChange guifg=#FFB961 guibg=NONE guisp=NONE
highlight GitGutterDelete guifg=#EB65B9 guibg=NONE guisp=NONE
highlight GitSignsAdd guifg=#41B5C5 guibg=NONE guisp=NONE
highlight GitSignsChange guifg=#FFB961 guibg=NONE guisp=NONE
highlight GitSignsDelete guifg=#EB65B9 guibg=NONE guisp=NONE
highlight Identifier guifg=#FFFFFF guibg=NONE guisp=NONE
highlight! link CmpItemKindVariable Identifier
highlight Inverse guifg=NONE guibg=NONE guisp=NONE
highlight! link Cursor Inverse
highlight! link IncSearch Inverse
highlight! link Substitute Inverse
highlight Italic guifg=NONE guibg=NONE guisp=NONE gui=italic cterm=italic
highlight Keyword guifg=#41B5C5 guibg=NONE guisp=NONE
highlight! link CmpItemKindKeyword Keyword
highlight LineNr guifg=#7C6A96 guibg=NONE guisp=NONE
highlight LspReferenceRead guifg=NONE guibg=#473851 guisp=NONE gui=underline cterm=underline
highlight LspReferenceText guifg=NONE guibg=#473851 guisp=NONE gui=underline cterm=underline
highlight LspReferenceWrite guifg=NONE guibg=#473851 guisp=NONE gui=underline cterm=underline
highlight MatchParen guifg=#EB65B9 guibg=NONE guisp=NONE gui=bold cterm=bold
highlight ModeCommand guifg=#FFE25F guibg=NONE guisp=NONE
highlight ModeInactive guifg=#7C6A96 guibg=NONE guisp=NONE
highlight ModeInsert guifg=#75DFC4 guibg=NONE guisp=NONE
highlight ModeMsg guifg=#7C6A96 guibg=NONE guisp=NONE gui=bold cterm=bold
highlight ModeNormal guifg=#41B5C5 guibg=NONE guisp=NONE
highlight ModeReplace guifg=#EB65B9 guibg=NONE guisp=NONE
highlight ModeVisual guifg=#B381C5 guibg=NONE guisp=NONE
highlight MoreMsg guifg=#41B5C5 guibg=NONE guisp=NONE
highlight! link Question MoreMsg
highlight NonText guifg=#7C6A96 guibg=NONE guisp=NONE
highlight! link CmpItemKindSnippet NonText
highlight! link LspCodeLens NonText
highlight! link LspCodeLensSeparator NonText
highlight! link LspSignatureActiveParameter NonText
highlight! link MsgArea NonText
highlight! link PreProc NonText
highlight! link TSPunctBracket NonText
highlight! link TSPunctDelimiter NonText
highlight! link TSPunctSpecial NonText
highlight! link TSStringSpecial NonText
highlight! link gitblame NonText
highlight NormalFloat guifg=#FFFFFF guibg=#251F2C guisp=NONE
highlight! link Pmenu NormalFloat
highlight! link PmenuSbar NormalFloat
highlight! link TabLineFill NormalFloat
highlight! link TelescopeNormal NormalFloat
highlight Number guifg=#B381C5 guibg=NONE guisp=NONE
highlight! link Float Number
highlight Operator guifg=#75DFC4 guibg=NONE guisp=NONE
highlight! link CmpItemKindField Operator
highlight! link CmpItemKindOperator Operator
highlight! link CmpItemKindProperty Operator
highlight! link Special Operator
highlight PmenuThumb guifg=NONE guibg=#7C6A96 guisp=NONE
highlight! link CmpItemKindModule PreProc
highlight QuickFixLine guifg=NONE guibg=#473851 guisp=NONE gui=bold cterm=bold
highlight Search guifg=#27212E guibg=#B381C5 guisp=NONE
highlight SignColumn guifg=#7C6A96 guibg=#27212E guisp=NONE
highlight SpellBad guifg=NONE guibg=NONE guisp=#FF3D7A gui=undercurl cterm=undercurl
highlight SpellCap guifg=NONE guibg=NONE guisp=#FFB961 gui=undercurl cterm=undercurl
highlight SpellLocal guifg=NONE guibg=NONE guisp=#41B5C5 gui=undercurl cterm=undercurl
highlight SpellRare guifg=NONE guibg=NONE guisp=#91889B gui=undercurl cterm=undercurl
highlight Statement guifg=#41B5C5 guibg=NONE guisp=NONE gui=italic cterm=italic
highlight! link CmpItemKindValue Statement
highlight! link Define Statement
highlight! link Include Statement
highlight! link Macro Statement
highlight! link PreCondit Statement
highlight StatusLine guifg=#FFFFFF guibg=#251F2C guisp=NONE
highlight! link TabLine StatusLine
highlight StatusLineNC guifg=#7C6A96 guibg=#251F2C guisp=NONE
highlight String guifg=#B3DBE6 guibg=NONE guisp=NONE
highlight TSKeyword guifg=#41B5C5 guibg=NONE guisp=NONE gui=italic cterm=italic
highlight TSStringEscape guifg=#B381C5 guibg=NONE guisp=NONE
highlight TSStringRegex guifg=#41B5C5 guibg=NONE guisp=NONE
highlight TSVariable guifg=#FFFFFF guibg=#27212E guisp=NONE
highlight TabLineSel guifg=#27212E guibg=#EB65B9 guisp=NONE
highlight TelescopeBorder guifg=#EB65B9 guibg=#251F2C guisp=NONE
highlight Title guifg=#41B5C5 guibg=NONE guisp=NONE gui=bold cterm=bold
highlight Todo guifg=#FFE25F guibg=NONE guisp=NONE
highlight Type guifg=#B381C5 guibg=NONE guisp=NONE
highlight! link CmpItemKindClass Type
highlight! link CmpItemKindEnum Type
highlight! link CmpItemKindEnumMember Type
highlight! link CmpItemKindEvent Type
highlight! link CmpItemKindInterface Type
highlight! link CmpItemKindStruct Type
highlight! link CmpItemKindTypeParameter Type
highlight! link CmpItemKindUnit Type
highlight! link TSTypeBuiltin Type
highlight Undercurl guifg=NONE guibg=NONE guisp=NONE gui=undercurl cterm=undercurl
highlight Underlined guifg=NONE guibg=NONE guisp=NONE gui=underline cterm=underline
highlight VertSplit guifg=#EB65B9 guibg=NONE guisp=NONE
highlight Visual guifg=NONE guibg=#473851 guisp=NONE
highlight! link PmenuSel Visual
highlight! link VisualNOS Visual
highlight! link WildMenu Visual
highlight WarningMsg guifg=#FFB961 guibg=NONE guisp=NONE
highlight Whitespace guifg=#7C6A96 guibg=NONE guisp=NONE
highlight diffAdded guifg=#41B5C5 guibg=NONE guisp=NONE
highlight diffChanged guifg=#FFB961 guibg=NONE guisp=NONE
highlight diffFile guifg=#FFE25F guibg=NONE guisp=NONE
highlight diffIndexLine guifg=#91889B guibg=NONE guisp=NONE
highlight diffLine guifg=#91889B guibg=NONE guisp=NONE
highlight diffNewFile guifg=#41B5C5 guibg=NONE guisp=NONE
highlight diffOldFile guifg=#EB65B9 guibg=NONE guisp=NONE
highlight diffRemoved guifg=#EB65B9 guibg=NONE guisp=NONE
highlight healthError guifg=#FF3D7A guibg=NONE guisp=NONE
highlight healthSuccess guifg=#75DFC4 guibg=NONE guisp=NONE
highlight healthWarning guifg=#FFB961 guibg=NONE guisp=NONE
" theme end

" if has('terminal')
"     highlight! link StatusLineTerm StatusLine
"     highlight! link StatusLineTermNC StatusLineNC
"     let g:terminal_ansi_colors = [
"                 \ g:terminal_color_0,
"                 \ g:terminal_color_1,
"                 \ g:terminal_color_2,
"                 \ g:terminal_color_3,
"                 \ g:terminal_color_4,
"                 \ g:terminal_color_5,
"                 \ g:terminal_color_6,
"                 \ g:terminal_color_7,
"                 \ g:terminal_color_8,
"                 \ g:terminal_color_9,
"                 \ g:terminal_color_10,
"                 \ g:terminal_color_11,
"                 \ g:terminal_color_12,
"                 \ g:terminal_color_13,
"                 \ g:terminal_color_14,
"                 \ g:terminal_color_15
"                 \ ]
" endif
