local template = require("laserwave.transform.template")

return template.create([[
<?xml version="1.0" encoding="UTF-8"?>

<!-- GENERATED ON $date AT $time
#
# @author $author
# @license $license
# @upstream $upstream
#
# $blurb
-->

<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>$name</string>
  <key>semanticClass</key>
  <string>theme.dark.$name</string>
  <key>colorSpaceName</key>
  <string>sRGB</string>
  <key>gutterSettings</key>
	<dict>
		<key>background</key>
		<string>$bg</string>
		<key>divider</key>
		<string>$accent</string>
		<key>foreground</key>
		<string>$fg</string>
		<key>selectionBackground</key>
		<string>$selection_bg</string>
		<key>selectionForeground</key>
		<string>$selection_fg</string>
	</dict>
	<key>settings</key>
	<array>
		<dict>
			<key>settings</key>
			<dict>
				<key>background</key>
				<string>$bg</string>
				<key>caret</key>
				<string>$cursor_bg</string>
				<key>foreground</key>
				<string>$fg</string>
				<key>invisibles</key>
				<string>$ignore_fg</string>
				<key>lineHighlight</key>
				<string>$line_bg</string>
				<key>selection</key>
				<string>$selection_bg</string>
				<key>gutter</key>
				<string>$bg</string>
				<key>gutterForeground</key>
				<string>$ignore_fg</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Comment</string>
			<key>scope</key>
			<string>comment, punctuation.definition.comment</string>
			<key>settings</key>
			<dict>
        <key>fontStyle</key>
        <string>italic</string>
				<key>foreground</key>
				<string>$comment_fg</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>String</string>
			<key>scope</key>
			<string>string</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>$string_fg</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Number</string>
			<key>scope</key>
			<string>constant.numeric</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>$number_fg</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Character</string>
			<key>scope</key>
			<string>constant.character</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>$character_fg</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Built-in constant</string>
			<key>scope</key>
			<string>constant.language</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>$constant_fg</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Keyword</string>
			<key>scope</key>
			<string>keyword</string>
			<key>settings</key>
			<dict>
        <key>fontStyle</key>
        <string>italic</string>
				<key>foreground</key>
				<string>$keyword_fg</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Operator</string>
			<key>scope</key>
			<string>keyword.operator, support.function</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>$operator_fg</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Variable</string>
			<key>scope</key>
			<string>variable</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>$identifier_fg</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Storage</string>
			<key>scope</key>
			<string>storage</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string>italic</string>
				<key>foreground</key>
				<string>$keyword_fg</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Class name</string>
			<key>scope</key>
			<string>support.class, entity.name.class, entity.name.type.class, meta.class</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>$class_fg</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Function name</string>
			<key>scope</key>
			<string>entity.name.function</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>$function_fg</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Tag name</string>
			<key>scope</key>
			<string>entity.name.tag</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>$tag_fg</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Tag attribute</string>
			<key>scope</key>
			<string>entity.other.attribute-name</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>$attribute_fg</string>
			</dict>
		</dict>
    <dict>
			<key>name</key>
			<string>Selector</string>
			<key>scope</key>
			<string>meta.selector</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>$type_fg</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Library function</string>
			<key>scope</key>
			<string>support.function</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>$function_fg</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Library constant</string>
			<key>scope</key>
			<string>support.constant</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>$constant_fg</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Library class&#x2f;type</string>
			<key>scope</key>
			<string>support.type, support.class</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>$type_fg</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Invalid</string>
			<key>scope</key>
			<string>invalid</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string>underline</string>
				<key>foreground</key>
				<string>$error_fg</string>
			</dict>
		</dict>
    <dict>
			<key>name</key>
			<string>Inserted</string>
			<key>scope</key>
			<string>markup.inserted</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>$added_fg</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Deleted</string>
			<key>scope</key>
			<string>markup.deleted</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>$deleted_fg</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Changed</string>
			<key>scope</key>
			<string>markup.changed</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>$changed_fg</string>
			</dict>
		</dict>
	</array>
</dict>
</plist>
]])
