local syntax = require("laserwave.spec.syntax")

-- WIP: These group names lifted from: https://github.com/folke/tokyonight.nvim/blob/f247ee7/lua/tokyonight/theme.lua#L271
---@type LaserwaveSpec
--stylua: ignore
local semantics = {
  -- ["@lsp.type.boolean"]                      = "@boolean",
  -- ["@lsp.type.builtinType"]                  = "@type.builtin",
  -- ["@lsp.type.comment"]                      = "@comment",
  ["@lsp.type.decorator"]                    = "Define",
  -- ["@lsp.type.deriveHelper"]                 = "@attribute",
  -- ["@lsp.type.enum"]                         = "@type",
  -- ["@lsp.type.enumMember"]                   = "@constant",
  -- ["@lsp.type.escapeSequence"]               = "@string.escape",
  -- ["@lsp.type.formatSpecifier"]              = "@punctuation.special",
  -- ["@lsp.type.generic"]                      = "@variable",
  -- ["@lsp.type.interface"]                    = { fg = util:lighten(c.blue1, 0.7) },
  ["@lsp.type.keyword"]                      = "Type",
  ["@lsp.type.class"]                        = "Type",
  -- ["@lsp.type.lifetime"]                     = "@storageclass",
  -- ["@lsp.type.namespace"]                    = "@namespace",
  -- ["@lsp.type.number"]                       = "@number",
  -- ["@lsp.type.operator"]                     = "@operator",
  -- ["@lsp.type.parameter"]                    = "@parameter",
  -- ["@lsp.type.property"]                     = "@property",
  -- ["@lsp.type.selfKeyword"]                  = "@variable.builtin",
  -- ["@lsp.type.selfTypeKeyword"]              = "@variable.builtin",
  -- ["@lsp.type.string"]                       = "@string",
  -- ["@lsp.type.typeAlias"]                    = "@type.definition",
  -- ["@lsp.type.unresolvedReference"]          = { undercurl = true, sp = c.error },
  ["@lsp.type.variable"]                     = {}, -- use treesitter styles for regular variables,
  -- ["@lsp.typemod.class.defaultLibrary"]      = "@type.builtin",
  -- ["@lsp.typemod.enum.defaultLibrary"]       = "@type.builtin",
  -- ["@lsp.typemod.enumMember.defaultLibrary"] = "@constant.builtin",
  -- ["@lsp.typemod.function.defaultLibrary"]   = "@function.builtin",
  -- ["@lsp.typemod.keyword.async"]             = "@keyword.coroutine",
  -- ["@lsp.typemod.keyword.injected"]          = "@keyword",
  -- ["@lsp.typemod.macro.defaultLibrary"]      = "@function.builtin",
  -- ["@lsp.typemod.method.defaultLibrary"]     = "@function.builtin",
  -- ["@lsp.typemod.operator.injected"]         = "@operator",
  -- ["@lsp.typemod.string.injected"]           = "@string",
  -- ["@lsp.typemod.struct.defaultLibrary"]     = "@type.builtin",
  -- ["@lsp.typemod.type.defaultLibrary"]       = { fg = util:darken(c.blue1, 0.8) },
  -- ["@lsp.typemod.typeAlias.defaultLibrary"]  = { fg = util:darken(c.blue1, 0.8) },
  ["@lsp.typemod.variable.callable"]         = "Function",
  ["@lsp.typemod.variable.defaultLibrary"]   = "Constant",
  ["@lsp.typemod.variable.injected"]         = "Identifier",
  ["@lsp.typemod.variable.static"]           = "Constant",
}

return semantics
