local palette = require("laserwave.palette")

---@type laserwave.Groups
--stylua: ignore
local snacks = {
  SnacksDashboardDesc     = "Normal",
  -- SnacksDashboardDir      = { },
  -- SnacksDashboardFile     = { },
  SnacksDashboardFooter   = { fg = palette.GUTTER },
  SnacksDashboardHeader   = { fg = palette.INFO },
  SnacksDashboardIcon     = { fg = palette.STRING },
  -- SnacksDashboardKey      = { },
  -- SnacksDashboardNormal   = { },
  -- SnacksDashboardSpecial  = { },
  -- SnacksDashboardTerminal = { },
  -- SnacksDashboardTitle    = { },
  SnacksDashboardHeader1  = { fg = palette.gradient.Step1 },
  SnacksDashboardHeader2  = { fg = palette.gradient.Step2 },
  SnacksDashboardHeader3  = { fg = palette.gradient.Step3 },
  SnacksDashboardHeader4  = { fg = palette.gradient.Step4 },
  SnacksDashboardHeader5  = { fg = palette.gradient.Step5 },
  SnacksDashboardHeader6  = { fg = palette.gradient.Step6 },
  SnacksDashboardHeader7  = { fg = palette.gradient.Step7 },
  SnacksDashboardHeader8  = { fg = palette.gradient.Step8 },
  SnacksDashboardHeader9  = { fg = palette.gradient.Step9 },
  SnacksDashboardHeader10 = { fg = palette.gradient.Step10 },
  SnacksDashboardHeader11 = { fg = palette.gradient.Step11 },
  SnacksDashboardHeader12 = { fg = palette.gradient.Step12 },
  SnacksDashboardHeader13 = { fg = palette.gradient.Step13 },
  SnacksDashboardHeader14 = { fg = palette.gradient.Step14 },
  SnacksDashboardHeader15 = { fg = palette.gradient.Step15 },
  SnacksDashboardHeader16 = { fg = palette.gradient.Step16 },
  SnacksDashboardHeader17 = { fg = palette.gradient.Step17 },
  SnacksDashboardHeader18 = { fg = palette.gradient.Step18 },
  SnacksDashboardHeader19 = { fg = palette.gradient.Step19 },
  SnacksDashboardHeader20 = { fg = palette.gradient.Step20 },

  -- SnacksPickerGitStatus          = { },
  -- SnacksPickerGitStatusRenamed   = { },
  -- SnacksPickerGitStatusCopied    = { },
  SnacksPickerGitStatusDeleted   = { fg = palette.DELETE },
  SnacksPickerGitStatusUnmerged  = { fg = palette.ERROR },
  SnacksPickerGitStatusModified  = { fg = palette.CHANGE },
  SnacksPickerGitStatusAdded     = { fg = palette.ADD },
  SnacksPickerGitStatusStaged    = { fg = palette.INFO },
  -- SnacksPickerGitStatusUntracked = { },
  -- SnacksPickerGitStatusIgnored   = { },
}

return snacks
